---
git::configs:
  user.name: 'Nick Miller'
  user.email:'nick.miller@onyxpoint.com'
  push.default: 'simple'
  core.editor: 'nvim'

configdir: '/home/nick/src'

rvm::system_rubies:
  'ruby-2.0'
    default_use: true
  'ruby-2.1'
rvm::system_users:
  - nick
